Repository Dann2405/LedBuzz-Project, pull requests merged in 2025-01, with the labels that each got.

#2 Suporte ao Wokwi e adição funções de processamento dos comandos via UART
  .vscode/launch.json
  LedBuzz.c
  diagram.json
  wokwi.toml
Labels: good first issue

#5 Update README.md
  README.md
Labels: documentation

#9 Feat/buzzer
  LedBuzz.c
Labels: good first issue

#10 adcionando sons ao buzzer
  LedBuzz.c
Labels: good first issue, wontfix

#11 Documentação
  README.md
Labels: documentation
